name: Deploy static site to GitHub Pages 

on:
  push:
    branches:
      - main  # main branch push aagumbothu run aagum

permissions:
  contents: write       # workflow repo content read panna permission
  pages: write           # GitHub Pages deploy panna permission
  id-token: write        # optional, some actions require it

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build project
        run: |
          echo "No build step, using static HTML/CSS/JS"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ # root folder la irunthu deploy
